# Generated by Django 5.1.4 on 2026-03-27 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Online",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "online",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("email", models.CharField(blank=True, max_length=128)),
                ("win", models.IntegerField(default=0)),
                ("lose", models.IntegerField(default=0)),
                ("tie", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "player",
            },
        ),
        migrations.CreateModel(
            name="Dreamreal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("phonenumber", models.CharField(max_length=50)),
                (
                    "online",
                    models.ForeignKey(
                        db_constraint=False,
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.online",
                    ),
                ),
            ],
            options={
                "db_table": "dreamreal",
            },
        ),
    ]
